Missing argument fixed
Trying example on https://docs.streamlit.io/library/api-reference/charts/st.pydeck_chart and got this error :

TypeError: wrap() missing 1 required positional argument: 'widget'